spring:
  application:
    name: ordini-e-pagamenti-gateway
  cloud:
    gateway:
      routes:
        - id: gestione-ordini
          uri: http://${GESTIONE_ORDINI_HOST:localhost}:${GESTIONE_ORDINI_PORT:8080}
          predicates:
            - Path=/${PATH_ORDINI:ordini}/**
        - id: gestione-pagamenti
          uri: http://${GESTIONE_PAGAMENTI_HOST:localhost}:${GESTIONE_PAGAMENTI_PORT:8080}
          predicates:
            - Path=/${PATH_PAGAMENTI:pagamenti}/**

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

server:
  port: ${GATEWAY_PORT:8080}